"""create guest sessions table

Revision ID: 4a3807b35281
Revises: fc26257d737d
Create Date: 2026-07-22 11:28:27.011207
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "4a3807b35281"
down_revision: str | None = "fc26257d737d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "guest_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("identity_hash", sa.String(length=64), nullable=False),
        sa.Column("question_count", sa.Integer(), nullable=False),
        sa.Column("document_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_guest_sessions_identity_hash"),
        "guest_sessions",
        ["identity_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_guest_sessions_token_hash"),
        "guest_sessions",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_guest_sessions_token_hash"), table_name="guest_sessions")
    op.drop_index(op.f("ix_guest_sessions_identity_hash"), table_name="guest_sessions")
    op.drop_table("guest_sessions")
    # ### end Alembic commands ###
