"""remove guest document limit

Revision ID: aeb5d0e3e276
Revises: 5d66ff4b453a
Create Date: 2026-07-22 15:58:42.237425
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "aeb5d0e3e276"
down_revision: str | None = "5d66ff4b453a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("guest_sessions", "document_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "guest_sessions",
        sa.Column(
            "document_count",
            sa.Integer(),
            server_default=sa.text("0"),
            nullable=False,
        ),
    )
    op.alter_column(
        "guest_sessions",
        "document_count",
        server_default=None,
    )
    # ### end Alembic commands ###
